//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply
    {
        public int id { get; set; }
        public  int comment_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string reply_text { get; set; }
    
        public virtual comment comment { get; set; }
        public virtual user user { get; set; }
    }
}
